name: Build and release PDFium binaries for iOS and macOS
on:
  push:
    tags:
      - pdfium-apple-*
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [ios, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build PDFium ${{ matrix.target }}
        run: ./darwin/pdfium/build ${{ matrix.target }}
      - name: Upload PDFium artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdfium-${{ matrix.target }}
          path: ./darwin/pdfium/pdfium-${{ matrix.target }}.zip

  release:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Download iOS artifact
        uses: actions/download-artifact@v3
        with:
          name: pdfium-ios
          path: ./darwin/pdfium/
      - name: Download macOS artifact
        uses: actions/download-artifact@v3
        with:
          name: pdfium-macos
          path: ./darwin/pdfium/
      - name: Release PDFium
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.TOKEN_FOR_RELEASE }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: iOS/macOS PDFium prebuilt binary distribution for pdfrx (${{ github.ref_name }}).
          files: |
            ./darwin/pdfium/pdfium-ios.zip
            ./darwin/pdfium/pdfium-macos.zip
